name: health_monitor
description: A mobile health app for remote monitoring and telemedicine.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.0
  agora_rtc_engine: ^5.2.0
  charts_flutter: ^0.12.0
  flutter_local_notifications: ^16.0.0
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/